# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6f51c097233428d45cb61445495d3cc0c42ca4eb4b92f3e9b4d2f07e96e015a70b15d886ff19fd946aea75e59ab71ac76f7ac65e0ac955d0230f122baa5a0e3

test:
  secret_key_base: 699acf9b6dab8acea6c3ccfb26dfadd54e4990a7de9e40a6f0a33eba8fda28019ddff246dabffec469526a8c5e50a4fb0b7e2c857f7c25dfbf0050015d90e0ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
